# Generated by Django 3.2.10 on 2022-07-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SonicRing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('material', models.CharField(default='gold', max_length=100, null=True)),
                ('shape', models.CharField(default='round', max_length=100, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
